# Site settings
title: WangW Blog
SEOTitle: 王威的博客 | WangW Blog
header-img: img/home-bg.jpg
email: wangwei0206@mail.nwpu.edu.cn
description: "关于机器学习, 深度学习, 医学图像处理 | 王威，master student, 在读硕士 | 这里是 @WangW 的个人博客，与你一起。"
keyword: "王威, WangW王威, WangW, ilikewind, likewind, 王威的博客, WangW Blog, 博客, 个人网站, ML, Deep Learning, DL, Math"
url: "https://likewind.top"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     WangWPro
zhihu_username:     xiang-feng-yiyang-666
github_username:    ilikewind
twitter_username:   likewind # 爱情纪念日
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: false

# Netease settings
netease_comment: false

#2018-12-11添加gitalk
gitalk:
enable: true
owner: ilikewind
repo: Myblog
clientID: 2793192964754da25afa
clientSecret: 41e173c60ffd564a9cba3cd31a16c1668570630d
admin: iliwind

# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: likewind.top



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
   # {
       # title: "乱序",
        #href: "http://mida.re/"
    #},
]
