# Site settings
title: WangW Blog
SEOTitle: 王威的博客 | WangW Blog
header-img: img/home-bg.jpg
email: wangwei0206@mail.nwpu.edu.cn
description: "关于机器学习, 深度学习 | 王威，master student, 在读硕士 | 这里是 @ilikewind 的个人博客，与你一起。"
keyword: "王威, WangW王威, WangW, ilikewind, likewind, 王威的博客, WangW Blog, 博客, 个人网站, ML, Deep Learning, DL, Math"
url: "https://likewind.top"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
#weibo_username:     1ilewind
#zhihu_username:     xiang-feng-yiyang-666
github_username:    ilikewind
twitter_username:   likewind # 爱情纪念日
#facebook_username:  1ikewind
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-toc,jekyll-paginate,jekyll-admin, jekyll-seo-tag, jemoji]# 
  # - 
  



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: false

# Netease settings
netease_comment: false

#2018-12-11添加gitalk Do not use my repo!!!!!!
gitalk:
enable: true
owner: ilikewind
repo: Myblog
clientID: 2793192964754da25afa
clientSecret: 41e173c60ffd564a9cba3cd31a16c1668570630d
admin: iliwind

# Analytics settings
# Baidu Analytics 
ba_track_id: 4f9e5a8b624f9b335919292b2ac7e2db

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: likewind.top



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For man is man and master of his fate<br>享受努力的过程，把握步伐的方向"
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
   {
      title: "百度统计",
      href: "https://tongji.baidu.com/"
    },
    {
      title: "骨代谢研究室",
      href: "http://qianslab.com"
    },
    {
      title: "LAMDA(周志华)",
      href: "http://lamda.nju.edu.cn/CH.MainPage.ashx?AspxAutoDetectCookieSupport=1"
    },
    {
      title: "微软研究院",
      href: "https://www.msra.cn/zh-cn/connections"
    },
    {
      title: "微软研究院视觉组",
      href: "https://www.microsoft.com/en-us/research/group/visual-computing/"
    },
    {
      title: "TSAIL Group(朱军课题组)",
      href: "https://www.labxing.com/lab/286/members"
    },
    {
      title: "南开大学媒体计算实验室",
      href: "https://mmcheng.net/zh/"
    },
    {
      title: "卢湖川课题组",
      href: "http://ice.dlut.edu.cn/lu/index.html"
    },
    {
      title: "伯克利大学机器视觉小组",
      href: "https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/"
    },
    {
      title: "德雷塞尔大学生物医学计算小组",
      href: "https://www.cs.drexel.edu/~david/geom_biomed_comp.html#cell_sim"
    },
    {
      title: "MIT 计算机科学与人工智能实验室",
      href: "https://www.csail.mit.edu"
    },
    {
      title: "MIT 生物与机器学习实验室",
      href: "http://poggio-lab.mit.edu/"
    },
    {
      title: "MIT 认知科学实验室",
      href: "http://persci.mit.edu/"
    },
    {
      title: "俄勒冈州立大学医学工程医学图像研究组",
      href: "https://bme.osu.edu/research/bioimaging"
    },
    {
      title: "中科院机器视觉课题组",
      href: "http://vision.ia.ac.cn/zh/index_cn.html"
    }, 
    {
      title: "北京大学机器感知实验室",
      href: "http://www.klmp.pku.edu.cn/Faculty/Researcher.html"
    },
    {
      title: "红色石头",
      href: "http://redstonewill.com/"
    },
    {
      title: "李培华实验室-大连理工",
      href: "http://peihuali.org/home.html"
    }
]
